name: CI
on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Unzip plugin distribution
        run: unzip -o build/distributions/formatter-plugin-*.zip -d build/distributions

      - name: Pull existing image for layer cache
        run: docker pull nilsbaumgartner1994/idea-parser:latest

      - name: Build docker image
        run: docker build . -t nilsbaumgartner1994/idea-parser:latest --cache-from nilsbaumgartner1994/idea-parser:latest

      - name: Test image
        run: docker run --rm -v ${{ github.workspace }}:/data nilsbaumgartner1994/idea-parser --style CodeStyle.xml --dry --recursive src

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: funbiscuit
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker push nilsbaumgartner1994/idea-parser:latest
